### ISSUE TITLE
console outputs error when running the latest code

### ISSUE THREAD

**Issue by YunyiZhang** [ant-design-blazor/ant-design-pro-blazor#60]
Here's error message：

System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Row.OptimizeSize(Decimal windowWidth)
   at AntDesign.Row.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Row.OptimizeSize(Decimal windowWidth)
   at AntDesign.Row.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by ElderJames** [comment]
Fixed via https://github.com/ant-design-blazor/ant-design-blazor/pull/908
